import type { Metadata } from 'next'
import {
  Anek_Devanagari,
  Inter,
  Lato,
  Montserrat,
  Nunito_Sans,
  Onest,
  Poppins,
  Raleway
} from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { cn } from '@/lib/utils'

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: 'NeoSIIT | Sistema Integral de Información',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es'>
      <body
        className={cn(
          'antialiased bg-background text-foreground',
          inter.className
        )}
      >
        {' '}
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
